env = _JAVA_AWT_WM_NONREPARENTING,1
env = ANDROID_EMULATOR_USE_SYSTEM_LIBS,1
env = ANDROID_SDK_ROOT,/home/gabzu/Android/Sdk

execr-once = flatpak run app.zen_browser.zen
execr-once = spotify
execr-once = discord
#execr-once = easyeffects --gapplication-service
# execr-once = com.github.wwmm.easyeffects --gapplication-service
# execr-once = sleep 5 && cd /home/gabzu/.config/deej && ./deej-release
execr-once = sleep 5 && openrgb --startminimized -p Rosio
execr-once = sudo deepcool-digital-linux
exec-once = hyprpm reload -n
execr-once = hyprctl dispatch workspace 1
exec-once = sh -c 'f="$HOME/.local/state/ambxst/states.json"; mkdir -p "$(dirname "$f")"; if [ -s "$f" ]; then jq ". + {caffeine:true}" "$f" > "$f.tmp" && mv "$f.tmp" "$f"; else printf "%s" "{\"caffeine\":true}" > "$f"; fi; exec ambxst'
exec-once = exec localsend_app --hidden
